### ISSUE TITLE
DomainException: Default website is not defined in ... Unable to run UnitTests with magento/framework 101.0.4

### ISSUE THREAD

**Issue by janzaba** [fooman/magento2-dev-bootstrap#1]
Hello!
I'm unable to run UnitTest for module with magento/framework 101.0.4 (it works with 101.0.3)

After magento updates magento/framework to 101.0.4 I'm getting this error:

~~~
./vendor/bin/phpunit 
DomainException: Default website is not defined in 
vendor/magento/module-store/Model/WebsiteRepository.php:144
Stack trace:
#0 vendor/magento/module-store/Model/StoreResolver/Website.php(46): Magento\Store\Model\WebsiteRepository->getDefault()
#1 vendor/magento/module-store/Model/StoreResolver.php(140): Magento\Store\Model\StoreResolver\Website->getAllowedStoreIds(NULL)
#2 vendor/magento/module-store/Model/StoreResolver.php(126): Magento\Store\Model\StoreResolver->readStoresData()
#3 vendor/magento/module-store/Model/StoreResolver.php(89): Magento\Store\Model\StoreResolver->getStoresData()
#4 vendor/magento/module-store/Model/StoreManager.php(157): Magento\Store\Model\StoreResolver->getCurrentStoreId()
#5 generated/code/Magento/Store/Model/StoreManagerInterface/Proxy.php(119): Magento\Store\Model\StoreManager->getStore(NULL)
#6 vendor/magento/module-store/Model/Resolver/Store.php(29): Magento\Store\Model\StoreManagerInterface\Proxy->getStore(NULL)
#7 vendor/magento/framework/App/Config/ScopeCodeResolver.php(49): Magento\Store\Model\Resolver\Store->getScope(NULL)
#8 vendor/magento/framework/App/Config.php(69): Magento\Framework\App\Config\ScopeCodeResolver->resolve('stores', NULL)
#9 vendor/magento/framework/Session/Config.php(148): Magento\Framework\App\Config->getValue('web/cookie/cook...', 'stores')
#10 vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(111): Magento\Framework\Session\Config->__construct(Object(Magento\Framework\ValidatorFactory), Object(Magento\Framework\App\Config), Object(Magento\Framework\Stdlib\StringUtils), Object(Magento\Framework\App\Request\Http), Object(Magento\Framework\Filesystem), Object(Magento\Framework\App\DeploymentConfig), 'store', 'web/cookie/cook...')
#11 vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(66): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Framewo...', Array)
#12 vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#13 vendor/magento/framework/App/Response/Http.php(81): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#14 generated/code/Magento/Framework/App/Response/Http/Interceptor.php(14): Magento\Framework\App\Response\Http->__construct(Object(Magento\Framework\App\Request\Http), Object(Magento\Framework\Stdlib\Cookie\PhpCookieManager), Object(Magento\Framework\Stdlib\Cookie\CookieMetadataFactory), Object(Magento\Framework\App\Http\Context), Object(Magento\Framework\Stdlib\DateTime), NULL)
#15 vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(111): Magento\Framework\App\Response\Http\Interceptor->__construct(Object(Magento\Framework\App\Request\Http), Object(Magento\Framework\Stdlib\Cookie\PhpCookieManager), Object(Magento\Framework\Stdlib\Cookie\CookieMetadataFactory), Object(Magento\Framework\App\Http\Context), Object(Magento\Framework\Stdlib\DateTime), NULL)
#16 vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(66): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Framewo...', Array)
#17 vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#18 vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(144): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#19 vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(230): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'response', 'Magento\\Framewo...')
#20 vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('Magento\\Framewo...', Array, Array)
#21 vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Framewo...', Array, Array)
#22 vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...', Array)
#23 vendor/magento/framework/App/Bootstrap.php(232): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Framewo...', Array)
#24 vendor/fooman/magento2-dev-bootstrap/src/TestBootstrap.php(47): Magento\Framework\App\Bootstrap->createApplication('Magento\\Framewo...')
#25 vendor/fooman/magento2-dev-bootstrap/src/TestBootstrap.php(22): Fooman\Magento2DevBootstrap\TestBootstrap->createApp()
#26 vendor/fooman/magento2-dev-bootstrap/src/bootstrap.php(4): Fooman\Magento2DevBootstrap\TestBootstrap->run()
#27 vendor/composer/autoload_real.php(70): require('/Users/janzaba/...')
#28 vendor/composer/autoload_real.php(60): composerRequire432518e46eb4d6ceebf33d12242765fb('8635c0143b403fd...', '/Users/janzaba/...')
#29 vendor/autoload.php(7): ComposerAutoloaderInit432518e46eb4d6ceebf33d12242765fb::getLoader()
#30 vendor/phpunit/phpunit/phpunit(51): require('/Users/janzaba/...')
#31 {main}
~~~

After some debugging and tracing new commits for framework I discovered the source. They added 
`Magento\Framework\Session\Config\ConfigInterface` in constructor of 
`Magento\Framework\App\Response\Http` and in it's constructor there is an assignment:
`$this->sessionConfig = $sessionConfig ?: ObjectManager::getInstance()->get(ConfigInterface::class);`

And this assignment gives us an error. So the big question is:
Is it something wrong with Magento, or we need to perform update for bootstrap to fulfill new di of that class?

Thanks for help in advance.

**Comment by fooman** [comment]
@janzaba Thanks for your feedback. I am still trying to work out the best way to line up this dev-bootstrap with Magento versions without a big overhead. My best guess for the issue that you ran into is that Magento made changes to app/etc/di.xml causing the missing class.

You could try replacing the 2.2.4 app/etc/di.xml from Magento and place it under
https://github.com/fooman/magento2-dev-bootstrap/blob/master/src/etc/di.xml

Please let me know how you are getting on.

**Comment by janzaba** [comment]
I've tried and it stil doesn't work.. 

I'm using Magento 2.2.3

**Comment by janzaba** [comment]
Hello!
I finally found the solution for this problem. I've created pull request for that.

https://github.com/fooman/magento2-dev-bootstrap/pull/2
